name: Install Python 3.13 on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    strategy:
        fail-fast: false
        matrix:
            python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Python ${{ matrix.python-version }}
      run: |
        brew update
        brew install python@${{ matrix.python-version }}
        brew doctor